#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # Runs every night at 02:00 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: rustyconover/extension-ci-tools/.github/workflows/_extension_distribution.yml@508f5da8ce615be8a5e798d325d4bbb6bbcd06a7
    with:
      duckdb_version: v1.4-andium
      ci_tools_version: 508f5da8ce615be8a5e798d325d4bbb6bbcd06a7
      override_ci_tools_repository: rustyconover/extension-ci-tools
      extension_name: lindel
      enable_rust: true
