#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Runs every night at 02:00 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  # duckdb-next-build:
  #   name: Build extension binaries
  #   uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
  #   with:
  #     duckdb_version: main
  #     ci_tools_version: main
  #     enable_rust: true
  #     extension_name: lindel
  #     exclude_archs: "windows_amd64_rtools"

  duckdb-stable-build:
    if: github.ref == 'main'
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: main
      ci_tools_version: main
      extension_name: lindel
      enable_rust: true
      exclude_archs: "windows_amd64_rtools;wasm_mvp;wasm_eh;wasm_threads"

  duckdb-stable-build-v1_3:
    if: github.ref == 'v1.3'
    name: Build extension binaries for 1.3
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: v1.3-ossivalis
      ci_tools_version: main
      extension_name: lindel
      enable_rust: true
      exclude_archs: "windows_amd64_rtools;wasm_mvp;wasm_eh;wasm_threads"

